export enum PatientPermission {
  MANAGE_SURVEY = "MANAGE_SURVEYS",
  GET_SURVEY = "GET_SURVEYS",
  STORE_LAB_RESULTS = "STORE_LAB_RESULTS",
  GET_LAB_RESULTS = "GET_LAB_RESULTS",
  PAY_FOR_TREATMENT = "PAY_FOR_TREATMENT",
  GET_TREATMENT_PACKAGE_OFFER = "GET_TREATMENT_PACKAGE_OFFER",
  GET_AVAILABILITY = "GET_AVAILABILITY",
  SCHEDULE_MEETING = "SCHEDULE_MEETING",
  GET_MEETING = "GET_MEETING",
  GET_TREATMENT_PACKAGE = "GET_TREATMENT_PACKAGE",
  GET_PAYMENT = "GET_PAYMENT",
}
