export enum RoutePermission {
  CREATE_WEDDING_ACCESS_KEY = "CREATE_WEDDING_ACCESS_KEY",
  CREATE_WEDDING = "CREATE_WEDDING",
  GET_WEDDING = "GET_WEDDING",
  GET_WEDDING_GUEST_CREDENTIALS = "GET_WEDDING_GUEST_CREDENTIALS",
  UPDATE_WEDDING = "UPDATE_WEDDING",
  PUT_PHOTO = "PUT_PHOTO",
}
