export enum Permission {
  CREATE_PRODUCT = "PRODUCT:CREATE",
  GET_PRODUCT = "PRODUCT:GET",
  DELETE_PRODUCT = "PRODUCT:DELETE",
  PUT_PRODUCT = "PRODUCT:PUT",
  CREATE_PRODUCT_IMAGE = "PRODUCT_IMAGE:CREATE",
}