export enum Permission {
  CREATE_PRODUCT = "PRODUCT:CREATE",
  GET_PRODUCT = "PRODUCT:GET",
  DELETE_PRODUCT = "PRODUCT:DELETE",
  PUT_PRODUCT = "PRODUCT:PUT",
  CREATE_PRODUCT_IMAGE = "PRODUCT_IMAGE:CREATE",
  GET_FILE = "FILE:GET",
  GET_CART = "CART:GET",
  PUT_CART_STATE = "CART:PUT_STATE",
  PUT_CART_PRODUCT = "CART:PUT_PRODUCT",
  DELETE_CART_PRODUCT = "CART:DELETE_PRODUCT",
  CREATE_CART_ORDER = "CART:CREATE_ORDER",
  CREATE_ORDER_PAYMENT = "ORDER_PAYMENT:CREATE",
}